if: type != push
language: node_js
node_js:
  - 8
install:
  - "make distclean"
  - "make build-tools"
script:
  - "make clean"
  - "make"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: gh-pages
branches:
  only:
    - gh-pages
    - /.*/
