# Don't change these
theme: jekyll-theme-primer
spec_server: specs.amwa.tv

# AMWA ID
amwa_id: NMOS-TESTING

# Base name for site (typically lower case version of AMWA ID, or the repo name)
baseurl: /nmos-testing

# Which release or branch appears in header links and on the home page
default_tree: branches/master

# Regex patterns of releases and branches to show
show_releases:
show_branches: ^master$|^publish-
