name: Lint
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Lint python
        run: |
          pip install flake8
          flake8 .
      - name: Setup for documentation lint
        run: make -C .lint distclean build-tools
      - name: Lint documentation
        run: make -C .lint lint
