name: Lint
on:
  workflow_dispatch:

  pull_request:

  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Setup for python lint
        run: pip install flake8
      - name: Lint python
        run: flake8 . 
      - name: Setup for documentation lint
        run: make -C .lint distclean build-tools
      - name: Lint documentation
        run: make -C .lint lint
